### ISSUE TITLE
global: refactor API

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-pidrelations#13]
API should be node-centric only, and instantiated with a pid (node) and relation_type.

```
class PIDNode:
   """Node can have multiple parents and multiple children for given relation_type.
      We look only at direct children/parents (directed incoming and outgoing edges)."""
   __init__(pid, relation_type)
   parents()  # All parents of the PID in given relation_type
   children()  # All direct children of the PID in given relation_type
   is_parent()  # Does given PID have any children
   is_child()  # Does given PID have any parents
   insert_child(pid)  # Not possible to insert with index

class PIDTreeNode(PIDNode):
   """Assume single parent."""
   parents()  # raises Exception (NotImplementedError?) - the "parents" are no longer defined for this API.
   parent()  # Return the single parent (i.e. super.parents().one_or_none())

class PIDOrderedTreeNode(PIDTreeNode):
   """Further assumes ordered children, introduces order-aware methods.""""
   children()
   last_child()  # Return   children().ordered('desc').first()  -  see "PIDQuery" class below
   is_last_child(pid)  # Return   self.last_child() == pid
   index(pid)
   next_child(pid)
   previous_child(pid)
   insert_child(pid, index)  # Required to provide an index
```
There will be two APIs related to versioning now, "NextVersion" for capturing the "next" versions only (Currently called RecordDraft, which stores information on "draft_child", and "draft_child_deposit" pids), and API for the versioning (PIDVersioning). NextVersion API will be composed inside PIDVersioning API
```
class contrib.versioning.NextVersion(PIDTreeNode):
   """A small tree with one parent and two children - next version recid and depid:
       (parent)
          /     \
   (recid)  (depid)
    """
   def init(pid):
      # in the diagram above, if you pass the (parent), you can then get two other children individually.
   def depid():
      # Query for children which are pid_type='depid', and return one_or_none()
   def recid():
      # Query for children which are pid_type='recid', and return one_or_none()

class contrib.versioning.PIDVersioning(PIDOrderedTreeNode):
   """Version-specific api."""
   __init__(pid)  # relation_type is resolved internally
   def next_version()  # returns a "NextVersion" PID instantiated with the self.pid
   def create_next_version(recid, depid)  # Create the two relations from PIDVersion API above
   def publish_next_version()  # Destroys the PIDVersion API above and "promotes" recid PID to a child in this relation.
```
Problem with kwargs in get_children(status=..., ordered=True/False) - i.e. putting parameters into signature vs filtering of the result with sqlalchemy (long, requires knowledge of model and sqlalchemy)

Children-querying methods (get_children) will no longer have kwargs ``ordered`` and ``status``. Instead a new Query class is to be defined, and all instances returned by API will be of this class, namely:

**Since "children()" no longer accepts kwargs, it can remain a property**, similarly "last_child/is_last_child" can remain properties.
```
class PIDQuery(sqlachemy.orm.BaseQuery):

   def ordered(ord='desc'):
      if ord not in ('asc', 'desc', ):
           raise
      ord_f = getattr(PIDRelation.index, ord)()
      return self.order_by(ord_f)

   def status(status_in):
      if isinstance(status_in, PIDStatus):
         status_in = [status_in,]
      return self.filter(PersistentIdentifier.status.in_(status_in))
```

**Comment by krzysztof** [comment]
@nharraud After discussing with @lnielsen we propose the following refactoring. This goes in the way of making API node-centric, instead of "edge + stuff around it" as it is now, which was probably the reason the API was confusing in the first place. It's not the refactoring we have discussed before, but we think it resolves the core issues you have highlighted equally well (confusing API method names, unclear "state" of the API object and it's fields), without introducing any restrictions like we discussed (e.g. single parent-only PIDConcept only). Also the class naming will suggest that it's a Node-centric API.

Please take a look if you have a moment.

**Comment by nharraud** [comment]
@krzysztof @lnielsen @slint thanks for the new design idea. It indeed improves the intuitiveness a lot.

I just see a few issues which we can discuss:
- we don't use `recid` as the PIDType of our records in B2SHARE.
- "unimplementing" a method in a subclass, as suggested for `parents` in `PIDTreeNode`, is not something commonly done. Couldn't we instead return a list of one parent in `PIDTreeNode`? It woudn't go against the doc of `parents` as it would still return the list of all parents.

**Comment by krzysztof** [comment]
>  we don't use recid as the PIDType of our records in B2SHARE.

Instead of using recid/depid in the NextVersion we can use two relation types instead

**Comment by krzysztof** [comment]
> "unimplementing" a method in a subclass, as suggested for parents in PIDTreeNode, is not something commonly done. Couldn't we instead return a list of one parent in PIDTreeNode? It woudn't go against the doc of parents as it would still return the list of all parents.

:+1: Can return a list of single parent, @lnielsen wdyt?
