### ISSUE TITLE
global: invalid copyrights years

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-pidrelations#2]
**Problem:**
[Some files](https://github.com/krzysztof/invenio-pidrelations/blob/9010eec050d338ab81c8f68ce615f911e9d97479/invenio_pidrelations/api.py#L4) have copyright years in the past and don't include 2017 even thought they were created that year.

**Comment by ntarocco** [comment]
I think this can be closes since we have changed the license and updated the headers.
